# Generated by Django 4.2.5 on 2023-09-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='r_con',
            new_name='Enter_your_thoughts',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='r_mail',
            new_name='Mail',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='r_name',
            new_name='Name',
        ),
    ]
