# Generated by Django 4.2.5 on 2023-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_rename_r_con_review_enter_your_thoughts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mov_img1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mov_img2',
            field=models.URLField(),
        ),
    ]
